### ISSUE TITLE
Error: Cannot read properties of null (reading '0')

### ISSUE THREAD

**Issue by veitbjarsch** [rowyio/roadmap#8]
Tried to install the application as descibed int the readme. Installation was fine and everything shows normal as anonymous user. But if I try to login with google I receive the following error:

Website:
<img width="378" alt="image" src="https://github.com/rowyio/roadmap/assets/12811012/e5db5419-2488-4de6-9281-bbc80c602b08">

Logs:
<img width="590" alt="image" src="https://github.com/rowyio/roadmap/assets/12811012/a26aa996-078d-4aaf-953f-aa82b57d334d">

**Comment by babakhalid** [comment]
Hi @veitbjarsch,

I had the same error, I fix it by changing the lines 11-14 in the file app/components/error/MissingFirestoreIndex.tsx to this :    
`const link =
    error.details.match(
      /(http|https):\/\/([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:\/~+#-]*[\w@?^=%&\/~+#-])/
    )?.[0] ?? "";`

**Comment by Clobbe** [comment]
> Hi @veitbjarsch,
> 
> I had the same error, I fix it by changing the lines 11-14 in the file app/components/error/MissingFirestoreIndex.tsx to this : `const link = error.details.match( /(http|https):\/\/([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:\/~+#-]*[\w@?^=%&\/~+#-])/ )?.[0] ?? "";`

I had the same issue, however this suggestion from @babakhalid did the trick - great stuff 🙌 🌟
